version: '3.4'
services:
  web1:
    image: zgchuck/infojob-web
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - 18080:80
    hostname: web1
    networks:
      infojob:
        ipv4_address: 172.24.0.4
        
  web2:
    image: zgchuck/infojob-web
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - 19080:80
    hostname: web2
    networks:
      infojob:
          ipv4_address: 172.24.0.5

  lb1:
    image: zgchuck/infojob-lb1
    build:
      context: .
      dockerfile: ./lb/lb1/Dockerfile
    sysctls:
      - net.ipv4.ip_nonlocal_bind=1
    ports:
      - 28080:8080
      - 28090:8090
    hostname: lb1
    privileged: true
    networks:
      infojob:
          ipv4_address: 172.24.0.2

  lb2:
    image: zgchuck/infojob-lb2
    build:
      context: .
      dockerfile: ./lb/lb2/Dockerfile
    sysctls:
      - net.ipv4.ip_nonlocal_bind=1
    ports:
      - 29080:8080
      - 29090:8090
    hostname: lb2
    privileged: true
    networks:
      infojob:
          ipv4_address: 172.24.0.3

  ansible:
    image: zgchuck/ansible
    build:
      context: .
      dockerfile: ./ansible/Dockerfile
    hostname: ansible
    privileged: true
    networks:
      infojob:
          ipv4_address: 172.24.0.8
    tty: true


networks:
  infojob:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.24.0.0/16

