---
- hosts: origin
  tasks:
  - name: Synchronization of src on the inventory host to the dest on the localhost in pull mode
    synchronize:
      mode: pull
      src: /tmp/
      dest: /ansible/ssl
      recursive: yes

- hosts: destination
  tasks:
  - name: Synchronization of src on delegate host to dest on the current inventory host.
    synchronize:
      src: /ansible/ssl/
      dest: /tmp/
      recursive: yes
    delegate_to: localhost
    notify: 
    - reload_haproxy

  handlers:
  - name: reload_haproxy 
    service:
      name: haproxy
      state: reloaded
